name: assignment
description: "모 회사 과제"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dart utility
  collection: ^1.18.0

  # core
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.1
  get_storage: ^2.1.1

  # annotation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  retrofit: ^4.1.0

  # ui
  cached_network_image: ^3.3.1
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  flutter_keyboard_visibility: ^6.0.0

  # custom
  carbonic_utility: ^0.0.1
  carbonic_logger: ^0.0.2
  carbonic_ui_kit: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8 # dart run build_runner build --delete-conflicting-outputs

  # lint
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.10

  # generator
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
